#!/bin/bash


# Usage:
#   bartermapp [arg1] [arg2]
#      arg1: terminal program to run
#      arg2: number of times do apply additional 
#            x offset defined by xinterval

# Dependencies:
#   tdrop


xoffset=15
xinterval=75
yoffset=-670
width=800
height=600
terminal=urxvt


x=$(expr $xoffset + $xinterval \* $2 - $xinterval)

w=$(expr $width + $3)

tdrop -a -w $w -h $height -x $x -y $yoffset -n $2 -f "-name $1 -e sh -c '$1'" $terminal &>/dev/null

# tval=$(~/.scripts_custom/control-tab.sh $2)

# if [ $tval == 0 ]; then
# 	echo "%{F#666 B#121212} $2%{F- B-}%{B#121212} $3 %{B-}"
# else
# 	echo "%{F#666 B#1e1e20} $2%{F- B-}%{B#1e1e20} %{F#86ffa4}$3 %{B- F-}"
# fi
