#!/bin/bash
i3lock --nofork                 \
    --ignore-empty-password	\
    --linecolor=00000000        \
    --keyhlcolor=985effff       \
    --bshlcolor=d23c3dff	\
    --separatorcolor=00000000   \
    --radius=15		\
    --indpos="x+86:y+1350"		\
    \
    --insidevercolor=fecf4dff	\
    --insidewrongcolor=d23c3dff \
    --insidecolor=373445ff	\
    \
    --ringcolor=ffffffff        \
    --ringvercolor=ffffffff     \
    --ringwrongcolor=ffffffff   \
    \
    --datestr="%^B%e" \
    --date-font="SF UI Display:style=heavy"	\
    --datesize=300		\
    --datepos="x+1080:y+500"	\
    --datecolor=ffffff4f	\
    \
    --greetertext=$(echo `date +"%A"`) \
    --greeter-font="ScriptinaBold" \
    --greetersize=240 \
    --greetercolor=f1fa6cff \
    --greeterpos="x+1080:y+500" \
    \
    --force-clock			\
    --timestr="·%H%M·"\
    --time-font="Iosevka Custom:style=bold"	\
    --timesize=30		\
    --timepos="x+1080:y+900"		\
    \ # --timecolor=24d1e777	\
    --timecolor=ffffffff \
    \
    --veriftext=""		\
    --wrongtext=""		\
    --noinputtext=""    \
    \
    --image=/usr/share/backgrounds/lockedwallpaper2.png \
    --tiling
