#!/bin/bash

i3lock -n -i /usr/share/backgrounds/lockedwallpaper2.jpg \
   --insidecolor=373445ff --ringcolor=ffffffff --line-uses-inside \
   --keyhlcolor=d23c3dff --bshlcolor=d23c3dff --separatorcolor=00000000 \
   --insidevercolor=fecf4dff --insidewrongcolor=d23c3dff \
   --ringvercolor=ffffffff --ringwrongcolor=ffffffff --indpos="x+86:y+1350" \
   --radius=15 --veriftext="" --wrongtext="" --noinputtext="..."

